In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("garments_worker_productivity.csv")
data.head()

date   quarter  department       day  team  targeted_productivity  \
0  1/1/2015  Quarter1      sweing  Thursday     8                   0.80   
1  1/1/2015  Quarter1  finishing   Thursday     1                   0.75   
2  1/1/2015  Quarter1      sweing  Thursday    11                   0.80   
3  1/1/2015  Quarter1      sweing  Thursday    12                   0.80   
4  1/1/2015  Quarter1      sweing  Thursday     6                   0.80   

     smv     wip  over_time  incentive  idle_time  idle_men  \
0  26.16  1108.0       7080         98        0.0         0   
1   3.94     NaN        960          0        0.0         0   
2  11.41   968.0       3660         50        0.0         0   
3  11.41   968.0       3660         50        0.0         0   
4  25.90  1170.0       1920         50        0.0         0   

   no_of_style_change  no_of_workers  actual_productivity  
0                   0           59.0             0.940725  
1                   0            8.0             0.886500  
2                   0           30.5             0.800570  
3                   0           30.5             0.800570  
4                   0           56.0             0.800382

In [10]:
X = data.drop("date", axis=1)
X = X.drop("actual_productivity", axis=1)
X = X.drop("wip", axis=1)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   quarter                1197 non-null   object 
 1   department             1197 non-null   object 
 2   day                    1197 non-null   object 
 3   team                   1197 non-null   int64  
 4   targeted_productivity  1197 non-null   float64
 5   smv                    1197 non-null   float64
 6   over_time              1197 non-null   int64  
 7   incentive              1197 non-null   int64  
 8   idle_time              1197 non-null   float64
 9   idle_men               1197 non-null   int64  
 10  no_of_style_change     1197 non-null   int64  
 11  no_of_workers          1197 non-null   float64
dtypes: float64(4), int64(5), object(3)
memory usage: 112.3+ KB


In [7]:
Y = data["actual_productivity"].values
Y

array([0.94072542, 0.8865    , 0.80057049, ..., 0.625625  , 0.50588889,
       0.39472222])

In [11]:
X["quarter"] = [int(x[-1]) for x in X["quarter"]]

In [13]:
X["department"] = [x.strip() for x in X["department"]]
X["department"] = [0 if x == "sweing" else 1 for x in X["department"]]
day_to_num = {"Sunday" : 0, "Monday": 1, "Tuesday": 2, "Wednesday": 3, "Thursday": 4, "Friday": 5, "Saturday": 6}
X["day"] = [day_to_num[x] for x in X["day"]]
X

quarter  department  day  team  targeted_productivity    smv  over_time  \
0           1           0    4     8                   0.80  26.16       7080   
1           1           1    4     1                   0.75   3.94        960   
2           1           0    4    11                   0.80  11.41       3660   
3           1           0    4    12                   0.80  11.41       3660   
4           1           0    4     6                   0.80  25.90       1920   
...       ...         ...  ...   ...                    ...    ...        ...   
1192        2           1    3    10                   0.75   2.90        960   
1193        2           1    3     8                   0.70   3.90        960   
1194        2           1    3     7                   0.65   3.90        960   
1195        2           1    3     9                   0.75   2.90       1800   
1196        2           1    3     6                   0.70   2.90        720   

      incentive  idle_time  idle_men  no_of_style_change  no_of_workers  
0            98        0.0         0                   0           59.0  
1             0        0.0         0                   0            8.0  
2            50        0.0         0                   0           30.5  
3            50        0.0         0                   0           30.5  
4            50        0.0         0                   0           56.0  
...         ...        ...       ...                 ...            ...  
1192          0        0.0         0                   0            8.0  
1193          0        0.0         0                   0            8.0  
1194          0        0.0         0                   0            8.0  
1195          0        0.0         0                   0           15.0  
1196          0        0.0         0                   0            6.0  

[1197 rows x 12 columns]

In [14]:
X.shape

(1197, 12)

In [15]:
def computeCost(x, y, w):
    noOfFeatures = x.shape[0] 
    loss = 0
    for i in range(noOfFeatures):
        f = w * x[i]
        loss = loss + (f - y[i])**2
    total_loss = 1 / noOfFeatures * loss
    return total_loss

In [17]:
def computeGradient(x, y, w): 
    noOfFeatures = x.shape[0]    
    dw = 0
    for i in range(noOfFeatures):  
        f = w * x[i] 
        dw += (f - y[i]) * x[i] 
    dw = 2* dw / noOfFeatures
        
    return dw

In [18]:
def computeGradientDescent(x, y, w, lr, num_iters): 
    for i in range(num_iters):
        dw = computeGradient(x, y, w)                    
        w = w - lr * dw                            
    return w

In [21]:
productivity = X["targeted_productivity"].values
productivity

array([0.8 , 0.75, 0.8 , ..., 0.65, 0.75, 0.7 ])

In [33]:
w = computeGradientDescent(productivity ,Y, 0, 0.5, 10000)
print(f"w: {w}")

w: 1.0029585238487935


In [34]:
w_loss = computeCost(productivity, Y, w)
print(f"feature = 1\tlr = 0.5\titers = 10000\tloss = {w_loss}")

feature = 1	lr = 0.5	iters = 10000	loss = 0.025630001743614916


In [35]:
w = computeGradientDescent(productivity ,Y, 0, 0.1, 10000)
print(f"w: {w}")

w: 1.0029585238487926


In [36]:
w_loss = computeCost(productivity, Y, w)
print(f"feature = 1\tlr = 0.1\titers = 10000\tloss = {w_loss}")

feature = 1	lr = 0.1	iters = 10000	loss = 0.02563000174361492


In [37]:
w = computeGradientDescent(productivity ,Y, 0, 0.01, 10000)
print(f"w: {w}")

w: 1.0029585238487835


In [38]:
w_loss = computeCost(productivity, Y, w)
print(f"feature = 1\tlr = 0.01\titers = 10000\tloss = {w_loss}")

feature = 1	lr = 0.01	iters = 10000	loss = 0.025630001743614884


In [39]:
w = computeGradientDescent(productivity ,Y, 0, 0.001, 10000)
print(f"w: {w}")

w: 1.0029389572372027


In [40]:
w_loss = computeCost(productivity, Y, w)
print(f"feature = 1\tlr = 0.001\titers = 10000\tloss = {w_loss}")

feature = 1	lr = 0.001	iters = 10000	loss = 0.02563000195109716


In [47]:
def computeCostN(X, y, w): 
    noOfFeatures = X.shape[0]
    loss = 0.0
    for i in range(noOfFeatures):                                
        f = np.dot(X[i], w)
        loss = loss + (f - y[i])**2
    loss = loss / noOfFeatures
    return loss

In [48]:
def computeGradientN(X, y, w): 
    noOfExamples,noOfFeatures = X.shape
    dw = np.zeros((noOfFeatures,))
    for i in range(noOfExamples):                             
        loss = np.dot(X[i], w) - y[i]   
        for j in range(noOfFeatures):                         
            dw[j] = dw[j] + loss * X[i, j]    
    dw = 2 * dw / noOfExamples                                
    return dw

In [49]:
def computeGradientDescentN(X, y, w, lr, num_iters): 
    for i in range(num_iters):
        dw = computeGradientN(X, y, w)
        w = w - lr * dw
    return w

In [64]:
three_features = X.drop("quarter", axis=1)
three_features = three_features.drop("department", axis=1)
three_features = three_features.drop("smv", axis=1)
three_features = three_features.drop("over_time", axis=1)
three_features = three_features.drop("targeted_productivity", axis=1)
three_features = three_features.drop("idle_time", axis=1)
three_features = three_features.drop("idle_men", axis=1)
three_features = three_features.drop("no_of_style_change", axis=1)
three_features = three_features.drop("no_of_workers", axis=1)
three_features = three_features.values
three_features

array([[ 4,  8, 98],
       [ 4,  1,  0],
       [ 4, 11, 50],
       ...,
       [ 3,  7,  0],
       [ 3,  9,  0],
       [ 3,  6,  0]])

In [65]:
x_rand = np.array([[0.3, 0.4, 0.5], [0.3, 0.4, 0.5], [0.3, 0.4, 0.5]])
y_rand = np.array([0.01, 0.02, 0.03])

In [69]:
w = np.array([0, 0, 0])
w = computeGradientDescentN(three_features, Y, w, 0.001, 100)
print(f"w: {w}")
w_loss = computeCostN(three_features, Y, w)
print(f"feature = 3\tlr = 0.5\titers = 100\tloss = {w_loss}")

w: [-1.30841222e+167 -3.88112224e+167 -4.34888418e+169]
feature = 3	lr = 0.5	iters = 100	loss = inf


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in double_scalars
  
